/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ff7290",
        "outline": "#9c677d",
        "on-error": "#ffefee",
        "surface-tint": "#b70049",
        "surface-container-high": "#ffd8e5",
        "on-error-container": "#570008",
        "error-container": "#fb5151",
        "secondary": "#176a21",
        "on-background": "#4a2134",
        "outline-variant": "#d89cb4",
        "on-tertiary-fixed-variant": "#563000",
        "on-primary-fixed": "#000000",
        "on-primary": "#ffeff0",
        "secondary-fixed": "#9df197",
        "background": "#fff4f6",
        "on-secondary-fixed": "#00460e",
        "secondary-fixed-dim": "#90e28a",
        "on-primary-container": "#4d001a",
        "secondary-dim": "#025d16",
        "on-surface-variant": "#7e4d61",
        "tertiary-fixed": "#ff9800",
        "surface-dim": "#ffc4da",
        "surface-variant": "#ffd1e1",
        "on-secondary-fixed-variant": "#12661e",
        "tertiary-dim": "#764400",
        "secondary-container": "#9df197",
        "surface-container-low": "#ffecf1",
        "primary-dim": "#a1003f",
        "primary": "#b70049",
        "tertiary-fixed-dim": "#ec8c00",
        "surface-container-highest": "#ffd1e1",
        "on-tertiary": "#fff0e5",
        "on-tertiary-fixed": "#271300",
        "on-secondary": "#d1ffc8",
        "tertiary-container": "#ff9800",
        "surface-bright": "#fff4f6",
        "primary-container": "#ff7290",
        "on-tertiary-container": "#4a2800",
        "surface-container": "#ffe0ea",
        "surface": "#fff4f6",
        "inverse-on-surface": "#c68da3",
        "error-dim": "#9f0519",
        "inverse-surface": "#220213",
        "inverse-primary": "#ff4e7c",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#4a2134",
        "on-secondary-container": "#005c15",
        "tertiary": "#874e00",
        "on-primary-fixed-variant": "#5f0022",
        "primary-fixed-dim": "#ff5580",
        "error": "#b31b25"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
